version: '3'

networks:
  proxy:
  services:
    internal: true

services:
  proxy-api:
      image: nginx
      container_name: proxy-api
      restart: unless-stopped
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      ports:
        - 80:80
      networks:
        - services
        - proxy
          #- api
          #   depends_on:
          #- app-forum-api
  service01:
    build: ./service01
    container_name: flask-api
    volumes:
      - ./service01/api.py

    ports:
      - 5000:5000
    networks:
      - services

    depends_on:
      - proxy-api

  
  service02:
    build: ./service02
    container_name: django-project
    volumes:
      - ./service02/
    ports:
      - 8000:8000
    networks:
      - services
    depends_on:
      - proxy-api